/**
 * Application error codes
 */

/**
 * Authentication errors (1xxx)
 */
export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'AUTH_1001',
  EMAIL_NOT_VERIFIED: 'AUTH_1002',
  ACCOUNT_SUSPENDED: 'AUTH_1003',
  ACCOUNT_LOCKED: 'AUTH_1004',
  TOKEN_EXPIRED: 'AUTH_1005',
  TOKEN_INVALID: 'AUTH_1006',
  REFRESH_TOKEN_EXPIRED: 'AUTH_1007',
  REFRESH_TOKEN_INVALID: 'AUTH_1008',
  INSUFFICIENT_PERMISSIONS: 'AUTH_1009',
  SESSION_EXPIRED: 'AUTH_1010',
  TWO_FACTOR_REQUIRED: 'AUTH_1011',
  TWO_FACTOR_INVALID: 'AUTH_1012',
} as const;

/**
 * User errors (2xxx)
 */
export const USER_ERRORS = {
  USER_NOT_FOUND: 'USER_2001',
  EMAIL_ALREADY_EXISTS: 'USER_2002',
  INVALID_EMAIL: 'USER_2003',
  WEAK_PASSWORD: 'USER_2004',
  PASSWORD_MISMATCH: 'USER_2005',
  USER_ALREADY_VERIFIED: 'USER_2006',
  VERIFICATION_TOKEN_INVALID: 'USER_2007',
  VERIFICATION_TOKEN_EXPIRED: 'USER_2008',
  RESET_TOKEN_INVALID: 'USER_2009',
  RESET_TOKEN_EXPIRED: 'USER_2010',
} as const;

/**
 * Company errors (3xxx)
 */
export const COMPANY_ERRORS = {
  COMPANY_NOT_FOUND: 'COMPANY_3001',
  COMPANY_ALREADY_EXISTS: 'COMPANY_3002',
  INVALID_COMPANY_NAME: 'COMPANY_3003',
  USER_LIMIT_REACHED: 'COMPANY_3004',
  DOMAIN_ALREADY_CLAIMED: 'COMPANY_3005',
  INVITATION_NOT_FOUND: 'COMPANY_3006',
  INVITATION_EXPIRED: 'COMPANY_3007',
  INVITATION_ALREADY_ACCEPTED: 'COMPANY_3008',
} as const;

/**
 * Subscription errors (4xxx)
 */
export const SUBSCRIPTION_ERRORS = {
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_4001',
  PLAN_NOT_FOUND: 'SUBSCRIPTION_4002',
  INVALID_PLAN: 'SUBSCRIPTION_4003',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_4004',
  PAYMENT_REQUIRED: 'SUBSCRIPTION_4005',
  PAYMENT_FAILED: 'SUBSCRIPTION_4006',
  CARD_DECLINED: 'SUBSCRIPTION_4007',
  INSUFFICIENT_FUNDS: 'SUBSCRIPTION_4008',
  TRIAL_ALREADY_USED: 'SUBSCRIPTION_4009',
  DOWNGRADE_NOT_ALLOWED: 'SUBSCRIPTION_4010',
  QUOTA_EXCEEDED: 'SUBSCRIPTION_4011',
  FEATURE_NOT_AVAILABLE: 'SUBSCRIPTION_4012',
} as const;

/**
 * Workflow errors (5xxx)
 */
export const WORKFLOW_ERRORS = {
  WORKFLOW_NOT_FOUND: 'WORKFLOW_5001',
  WORKFLOW_INVALID: 'WORKFLOW_5002',
  WORKFLOW_EXECUTION_FAILED: 'WORKFLOW_5003',
  WORKFLOW_TIMEOUT: 'WORKFLOW_5004',
  NODE_NOT_FOUND: 'WORKFLOW_5005',
  CIRCULAR_DEPENDENCY: 'WORKFLOW_5006',
  INVALID_TRIGGER: 'WORKFLOW_5007',
  EXECUTION_NOT_FOUND: 'WORKFLOW_5008',
  WORKFLOW_PAUSED: 'WORKFLOW_5009',
  MAX_EXECUTIONS_REACHED: 'WORKFLOW_5010',
} as const;

/**
 * Document errors (6xxx)
 */
export const DOCUMENT_ERRORS = {
  DOCUMENT_NOT_FOUND: 'DOCUMENT_6001',
  INVALID_FILE_TYPE: 'DOCUMENT_6002',
  FILE_TOO_LARGE: 'DOCUMENT_6003',
  UPLOAD_FAILED: 'DOCUMENT_6004',
  PROCESSING_FAILED: 'DOCUMENT_6005',
  STORAGE_QUOTA_EXCEEDED: 'DOCUMENT_6006',
  AI_SERVICE_UNAVAILABLE: 'DOCUMENT_6007',
  AI_REQUEST_FAILED: 'DOCUMENT_6008',
  CONVERSATION_NOT_FOUND: 'DOCUMENT_6009',
  MESSAGE_TOO_LONG: 'DOCUMENT_6010',
} as const;

/**
 * Integration errors (7xxx)
 */
export const INTEGRATION_ERRORS = {
  INTEGRATION_NOT_FOUND: 'INTEGRATION_7001',
  PROVIDER_NOT_SUPPORTED: 'INTEGRATION_7002',
  CONNECTION_FAILED: 'INTEGRATION_7003',
  OAUTH_ERROR: 'INTEGRATION_7004',
  INVALID_CREDENTIALS: 'INTEGRATION_7005',
  API_KEY_INVALID: 'INTEGRATION_7006',
  RATE_LIMIT_EXCEEDED: 'INTEGRATION_7007',
  SYNC_FAILED: 'INTEGRATION_7008',
  WEBHOOK_VERIFICATION_FAILED: 'INTEGRATION_7009',
  INTEGRATION_DISCONNECTED: 'INTEGRATION_7010',
} as const;

/**
 * Validation errors (8xxx)
 */
export const VALIDATION_ERRORS = {
  VALIDATION_FAILED: 'VALIDATION_8001',
  REQUIRED_FIELD_MISSING: 'VALIDATION_8002',
  INVALID_FORMAT: 'VALIDATION_8003',
  VALUE_TOO_SHORT: 'VALIDATION_8004',
  VALUE_TOO_LONG: 'VALIDATION_8005',
  VALUE_OUT_OF_RANGE: 'VALIDATION_8006',
  INVALID_ENUM_VALUE: 'VALIDATION_8007',
  INVALID_DATE: 'VALIDATION_8008',
  INVALID_URL: 'VALIDATION_8009',
  INVALID_JSON: 'VALIDATION_8010',
} as const;

/**
 * System errors (9xxx)
 */
export const SYSTEM_ERRORS = {
  INTERNAL_ERROR: 'SYSTEM_9001',
  DATABASE_ERROR: 'SYSTEM_9002',
  CACHE_ERROR: 'SYSTEM_9003',
  STORAGE_ERROR: 'SYSTEM_9004',
  QUEUE_ERROR: 'SYSTEM_9005',
  SERVICE_UNAVAILABLE: 'SYSTEM_9006',
  MAINTENANCE_MODE: 'SYSTEM_9007',
  CONFIGURATION_ERROR: 'SYSTEM_9008',
  NETWORK_ERROR: 'SYSTEM_9009',
  TIMEOUT: 'SYSTEM_9010',
} as const;

/**
 * All error codes
 */
export const ERROR_CODES = {
  ...AUTH_ERRORS,
  ...USER_ERRORS,
  ...COMPANY_ERRORS,
  ...SUBSCRIPTION_ERRORS,
  ...WORKFLOW_ERRORS,
  ...DOCUMENT_ERRORS,
  ...INTEGRATION_ERRORS,
  ...VALIDATION_ERRORS,
  ...SYSTEM_ERRORS,
} as const;

/**
 * Error messages
 */
export const ERROR_MESSAGES: Record<string, string> = {
  // Auth
  [AUTH_ERRORS.INVALID_CREDENTIALS]: 'Invalid email or password',
  [AUTH_ERRORS.EMAIL_NOT_VERIFIED]: 'Please verify your email address',
  [AUTH_ERRORS.ACCOUNT_SUSPENDED]: 'Your account has been suspended',
  [AUTH_ERRORS.TOKEN_EXPIRED]: 'Your session has expired',
  [AUTH_ERRORS.TOKEN_INVALID]: 'Invalid authentication token',
  [AUTH_ERRORS.INSUFFICIENT_PERMISSIONS]: 'You do not have permission to perform this action',

  // User
  [USER_ERRORS.USER_NOT_FOUND]: 'User not found',
  [USER_ERRORS.EMAIL_ALREADY_EXISTS]: 'Email address is already registered',
  [USER_ERRORS.WEAK_PASSWORD]: 'Password is too weak',

  // Company
  [COMPANY_ERRORS.COMPANY_NOT_FOUND]: 'Company not found',
  [COMPANY_ERRORS.USER_LIMIT_REACHED]: 'User limit reached for your plan',

  // Subscription
  [SUBSCRIPTION_ERRORS.PAYMENT_REQUIRED]: 'Payment is required',
  [SUBSCRIPTION_ERRORS.QUOTA_EXCEEDED]: 'Quota exceeded for your plan',
  [SUBSCRIPTION_ERRORS.FEATURE_NOT_AVAILABLE]: 'This feature is not available on your plan',

  // Workflow
  [WORKFLOW_ERRORS.WORKFLOW_NOT_FOUND]: 'Workflow not found',
  [WORKFLOW_ERRORS.WORKFLOW_EXECUTION_FAILED]: 'Workflow execution failed',

  // Document
  [DOCUMENT_ERRORS.DOCUMENT_NOT_FOUND]: 'Document not found',
  [DOCUMENT_ERRORS.FILE_TOO_LARGE]: 'File size exceeds maximum limit',
  [DOCUMENT_ERRORS.STORAGE_QUOTA_EXCEEDED]: 'Storage quota exceeded',

  // Integration
  [INTEGRATION_ERRORS.INTEGRATION_NOT_FOUND]: 'Integration not found',
  [INTEGRATION_ERRORS.CONNECTION_FAILED]: 'Failed to connect to service',

  // Validation
  [VALIDATION_ERRORS.VALIDATION_FAILED]: 'Validation failed',
  [VALIDATION_ERRORS.REQUIRED_FIELD_MISSING]: 'Required field is missing',

  // System
  [SYSTEM_ERRORS.INTERNAL_ERROR]: 'An internal error occurred',
  [SYSTEM_ERRORS.SERVICE_UNAVAILABLE]: 'Service is temporarily unavailable',
};